services:
  - type: web
    name: zero-hunger-hub
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
      - key: SECRET_KEY
    autoDeploy: true
    disk: 1024
    healthCheckPath: /
